version: "3.8"

services:
  app:
    image: testeestrutura-web:latest
    volumes:
      - /c/Users/muril/OneDrive/Ãrea\ de\ Trabalho/teste\ estrutura:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
